version: '3.8'

services:

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - TZ=Europe/Istanbul
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - TZ=Europe/Istanbul

  panel:
    build:
      context: .
      dockerfile: panel.Dockerfile
    container_name: panel
    depends_on:
      - jenkins
      - mongodb
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/staging
      - JENKINS_URL=http://jenkins:8080
      - SERVER_URL=http://server:3000
      - TZ=Europe/Istanbul
    restart: always

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: server
    depends_on:
      - jenkins
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/staging
      - JENKINS_URL=http://jenkins:8080
      - TZ=Europe/Istanbul
    restart: always

volumes:
  jenkins_home:
  mongodb_data:
